### ISSUE TITLE
documentation steps not working

### ISSUE THREAD

**Issue by brianmickel** [readmeio/oas#361]
Following the steps on https://openap.is/
1. set up the project
```
$ npm init # accept defaults
$ npm i -D oas
$ npx oas init
? Name of the API openapi
? Version number 1.0.0
? License ISC
? Full Base URL https://api.example.com
? Output JSON or YAML file 1.0.0.json
```
2. Create an `index.js` file with
```
/* @oas [post] /pets/{category}
 * description: "List all pets in a category"
 * parameters:
 * - (path) category=all* {String} Pet category
 * - (query) limit {Integer:int32} Amt returned
 * - (body) search {String} Search pet details
 * - (body) strict {Boolean} Exact matches?
 */

routes.get('/pets/:category', getPets);
```
3. run `npx oas generate './1.0.0.json'`
returns the following error
> Error: Error: No comment-part had a match. This should not happen

stacktrace:
>  at 1.0.0.json
    at /Users/brianmickel/experimental/openapi/node_modules/swagger-inline/build/swagger-inline.js:111:35
    at Array.map (<anonymous>)
    at /Users/brianmickel/experimental/openapi/node_modules/swagger-inline/build/swagger-inline.js:88:44
    at tryCatcher (/Users/brianmickel/experimental/openapi/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/brianmickel/experimental/openapi/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/brianmickel/experimental/openapi/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/brianmickel/experimental/openapi/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/brianmickel/experimental/openapi/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/brianmickel/experimental/openapi/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/brianmickel/experimental/openapi/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/brianmickel/experimental/openapi/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/brianmickel/experimental/openapi/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/brianmickel/experimental/openapi/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/brianmickel/experimental/openapi/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/brianmickel/experimental/openapi/node_modules/bluebird/js/release/promise.js:673:18)
    at MappingPromiseArray.PromiseArray._resolve (/Users/brianmickel/experimental/openapi/node_modules/bluebird/js/release/promise_array.js:127:19)

`1.0.0.json` contents:
```
{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "openapi",
    "license": {
      "name": "ISC"
    }
  },
  "servers": [
    {
      "url": "https://api.example.com"
    }
  ],
  "paths": {}
}
```

**Comment by mamatela** [comment]
Any progress on this one? Exactly the same issue here.

**Comment by erunion** [comment]
We haven't had a chance to prioritize this unfortunately but we're open to accepting a pull request if someone's able to look into it.

**Comment by xdmnl** [comment]
I am experiencing the same problem. After some tests it seems that this error only occurs when a JSON file is in the same folder as the files to parse.
A workaround is to either move the openapi json file outside of the folder where the code live or convert it to yaml.
