### ISSUE TITLE
oas generate cant load json

### ISSUE THREAD

**Issue by schumischumi** [readmeio/oas#500]
I cant run oas generate. If I do without any argument it asks me to generate a base file (it already exists) and if I run it with an argument (i.e. base.json or base.yaml) I get this error:
```
Error: TypeError: Cannot read properties of null (reading 'reduce') 
 at src/app_loader.py
    at /usr/lib/node_modules/oas/node_modules/swagger-inline/src/index.js:99:39
    at Array.map (<anonymous>)
    at /usr/lib/node_modules/oas/node_modules/swagger-inline/src/index.js:83:27
    at async Object.exports.findSwagger (/usr/lib/node_modules/oas/src/cli/lib/utils.js:48:31)
```

node: v16.9.1 
npm: 7.21.1

in the folder I try to run oas generate is a file app.py with these comments:
```
...
# @oas [get] /funct/{number1}/{number2}
# description: "great text"
# parameters:
# - (number1) Number1 {Integer:int32}  great desc for number 1
# - (number2) Number2 {Integer:int32} great desc for number 2

@app.route('/funct/<num1>/<num2>')
...
```

here is what I did step by step:
```
user@user-virtualbox:~/git/my-app/webapp$ oas init
This will help you set up an OpenAPI 3.0 Definition in your codebase, so
you can start documenting your API!

? Name of the API webapp
? Version number 1.0.0
? License no
? Full Base URL http://mockup.url.com/
? Output JSON or YAML file base.json

======================

SUCCESS!

We've created your new OpenAPI file at base.json.

You can document each endpoint right above the code. Just use the
following syntax in a comment above the code:

  """
  @oas [get] /pet/{petId}
  description: Returns all pets from the system that the user has access to
  parameters:
    - (path) petId=2* {Integer} The pet ID
    - (query) limit {Integer:int32} The number of resources to return
  """
  def getPet(id):

For more information on this syntax, see https://github.com/readmeio/swagger-inline

To see what you can do with your API, type oas help.

To generate an OAS file, type oas generate. To publish it, type oas host!

user@user-virtualbox:~/git/my-app/webapp$ oas generate
You must pass a base OpenAPI or Swagger definition into oas generate to build off of.

This base specification might look like the following:
{
  "openapi": "3.0.3",
  "info": {
    "title": "Example OpenAPI base file for `oas`.",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://api.example.com"
    }
  ]
}

And supply that to oas generate as oas generate openapiBase.json
user@user-virtualbox:~/git/my-app/webapp$ oas generate base.json
Error: TypeError: Cannot read properties of null (reading 'reduce') 
 at src/app_loader.py
    at /usr/lib/node_modules/oas/node_modules/swagger-inline/src/index.js:99:39
    at Array.map (<anonymous>)
    at /usr/lib/node_modules/oas/node_modules/swagger-inline/src/index.js:83:27
    at async Object.exports.findSwagger (/usr/lib/node_modules/oas/src/cli/lib/utils.js:48:31)
```

here is the content of the json file created by osa init:
```
{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "webapp",
    "license": {
      "name": "no"
    }
  },
  "servers": [
    {
      "url": "http://mockup.url.com/"
    }
  ],
  "paths": {}
}
```

thanks for you help!

**Comment by drussell-gmk** [comment]
@schumischumi i was having some issues as well with the generate command.  After looking through the code there might be an issue with the command running in the wrong directory.  I added the option --path with the path to the root of the project I am trying to generate docs for so maybe give that a try and see if that gets past your issue.  I still believe this to be an issue so I believe this should remain open.
